reviews:
  namespace: student38-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  image: ghcr.io/memorisza/bookinfo-reviews
  tag: prd
ingress:
  host: sitkmutt.bookinfo.opsta.net
  path: "/student38/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_SERVICE: "http://sitkmutt.bookinfo.opsta.net/student38/ratings"
  STAR_COLOR: "pink"
  ENABLE_RATINGS: "true"